version: 2

models: 

  - name: anc_case
    description: "merged model with case and last visit date"

  - name: anc_outcomes
    description: "merged model with case and delivery data"

  - name: anc_visit_by_month
    description: "Aggregated visits of cases by CO per month"
