version: 2

models:
  - name: anc_visit_normalized
    description: "Normalized data of ANC visit" 
    +schema: intermediate
    columns: 
       - name: _airbyte_ab_id
         description: "The primary key for this table"
         tests:
           - unique
           - not_null

  - name: anc_outcome_normalized
    description: "Normalized data of ANC Delivery Information visit" 
    +schema: intermediate
    columns: 
       - name: _airbyte_ab_id
         description: "The primary key for this table"
         tests:
           - unique
           - not_null

  - name: anc_referral_followup_normalized
    description: "Normalized data of ANC Referral Followups visit"
    +schema: intermediate
    columns: 
       - name: _airbyte_ab_id
         description: "The primary key for this table"
         tests:
           - unique
           - not_null

  - name: anc_registration_normalized
    description: "Normalized data of ANC Registrations" 
    +schema: intermediate
    columns: 
       - name: _airbyte_ab_id
         description: "The primary key for this table"
         tests:
           - unique
           - not_null

  - name: anc_case_normalized
    description: "Normalized model of ANC cases" 
    +schema: intermediate
    columns: 
       - name: _airbyte_ab_id
         description: "The primary key for this table"
         tests:
           - unique
           - not_null 

  - name: anc_visit_duplicates_removed
    description: "Deduped model of ANC visits"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: anc_outcome_duplicates_removed
    description: "Deduped model of ANC delivery information"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: anc_referral_followup_duplicates_removed
    description: "Deduped data of ANC Referral Followups visit"
    +schema: intermediate
    columns: 
       - name: id
         description: "The primary key for this table"
         tests:
           - unique
           - not_null

  - name: anc_registration_duplicates_removed
    description: "Deduped data of ANC Registrations" 
    +schema: intermediate
    columns: 
       - name: _airbyte_ab_id
         description: "The primary key for this table"
         tests:
           - unique
           - not_null

  - name: anc_case_duplicates_removed
    description: "Deduped model for ANC cases"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
