version: 2

sources:
  - name: commcare_anc
    schema: staging
    tables:
      - name: raw_anc_visit
        identifier: _airbyte_raw_anc_pnc_visit
        description: Visit data for ANC Program 
      - name: raw_referral_followup
        identifier: _airbyte_raw_referral_followup
        description: Referral followup data
      - name: raw_case
        identifier: _airbyte_raw_zzz_case
        description: Cases across entire Commcare application for form streams synced through airbyte