version: 2

models: 

  - name: anc_case
    description: "merged model with case and last visit date"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: anc_case_open
    description: "date spined case model giving status for each month the case is open"

  - name: anc_outcome
    description: "merged model with case and delivery data"
    
  - name: anc_referral_followup
    description: "merged model with case and referral followup data"

  - name: anc_visit
    description: " ANC visits of cases"

  - name: anc_visit_by_month
    description: "Aggregated visits of cases by CO per month"

  - name: anc_case_metrics
    description: "Case file Metrics defined throguh aggregations"

  - name: anc_metrics_definition
    description: "Metrics defined throguh raw queries"

  - name: anc_metrics_all_tmp
    description: "Metrics calculated to sum up across clusters - pre-calculated to deal with percentages"

  - name: anc_metrics_clustered_tmp
    description: "Temp  Metrics/KPIs clustered created to get around dbt ephemeral restrictions"

  - name: anc_metrics
    description: "Percentage Metrics/KPIs"

  - name: anc_metrics_monthly
    description: "Monthly Percentage Metrics/KPIs"

  - name: anc_metrics_normalized
    description: "Normalized Percentage Metrics/KPIs in long form instead of wide"

  - name: anc_metrics_normalized_monthly
    description: "Normalized Percentage Metrics/KPIs"
